"""Change Datatype Category

Revision ID: 90e2ed2f3f94
Revises: f543a2c9464d
Create Date: 2020-10-23 04:12:53.427280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e2ed2f3f94'
down_revision = 'f543a2c9464d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category_pitch', sa.String(), nullable=True))
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'category_pitch')
    # ### end Alembic commands ###
